### ISSUE TITLE
[FEAT] 스웨거 설명 추가 및 Valid 추가

### ISSUE THREAD

**Issue by catturtle123** [SMU-COSSTHON-43-9/BACK#16]
## Description
스웨거 설명 추가 및 Valid 추가

## To-do
- [ ] post 스웨거 설명 추가
- [ ] care 스웨거 설명 추가
- [ ] volunteer 스웨거 설명 추가
- [ ] valid 추가
