### ISSUE TITLE
[FEAT] 삭제 성공 DTO 추가

### ISSUE THREAD

**Issue by catturtle123** [SMU-COSSTHON-43-9/BACK#18]
## Description
삭제 성공 DTO 추가

## To-do
- [ ] post 삭제 성공 DTO 추가
- [ ] volunteer 삭제 성공 DTO 추가
- [ ] care 성공 DTO 추가
